{"success": true, "data": [{"team": {"name": "konohagakure", "id": 296}, "challenge_id": 1, "challenge": {"name": "\u25b6 Sanity Check", "value": 39, "id": 1, "category": "Misc"}, "date": "2024-08-23T16:13:19.760568+00:00", "id": 303, "user": {"name": "akito.404_error", "id": 20}, "type": "correct"}], "meta": {"count": 1}}
